### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 196607: invalid start byte

### ISSUE THREAD

**Issue by DanielEbert** [justfoxing/jfx_bridge#17]
Hello,

I want to remotify a function 'my_function' and return a very large object from my_function.
When I do this, I get the following output:
~~~
2022-02-17 12:04:47,842 [ERROR bridge.py:522 run()] 'utf-8' codec can't decode byte 0xaa in position 196607: invalid start byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jfx_bridge/bridge.py", line 504, in run
    msg_dict = json.loads(data.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 196607: invalid start byte
~~~

In the bridge.py file in function read_size_and_data_from_socket, I think the size of 'data' is stored in 32 bits. Maybe there is a problem if 'my_function' returns an object that is larger than 2**32 bytes (~4 Gigabytes)?

Let me know if you need more info.

**Comment by maxeisele** [comment]
Wow, that was fast. For now, the error has not occurred again, so I guess it is fixed. Thanks a lot!

**Comment by justfoxing** [comment]
Sweet! I'll close this now, but if it does reoccur, feel free to reopen.
